### ISSUE TITLE
Doesn't scroll when too big for viewport

### ISSUE THREAD

**Issue by tracker1** [juanbrujo/tinyModal#4]
If you open the second modal in the demo, then shrink the window down, the modal's area should scroll..

Here's an example[1] I have for a modal that works as one might expect.  When the modal is open, the page itself doesn't scroll, for those browsers/platforms with a visible scrollbar, the page is adjusted as appropriate, and when the viewport is too small for the modal (vertically) you can scroll just the modal portion of the viewport.

I have the structure for the outline here[2], as well as the complementing styles[3].

[1] http://tracker1.github.io/md-datepicker/
[2] https://github.com/tracker1/md-datepicker/blob/master/_src/DatePickerModal/feature/main/index.js
[3] https://github.com/tracker1/md-datepicker/blob/master/_src/DatePickerModal/feature/main/style.scss

**Comment by juanbrujo** [comment]
Thanks for the detailed point @tracker1. tinyModal was created as a modal-wrapper, delivering a very basic CSS markup to use it as starter. The problem you show is easily resolved adding an inner `<div>` container and adding, for example, `overflow-y: auto;`. I'll see if I add it to the default markup and create a new release.

Thanks again.

**Comment by juanbrujo** [comment]
resolved https://github.com/juanbrujo/tinyModal/commit/fa2b3da83dc0788a05c6ab25cf1a65a60db5e869
